lines = [
'import { useNavigate, Link } from "react-router-dom";',
'import { ArrowLeft, BookOpen, FileText, ExternalLink, Users, Phone, Mail, MapPin } from "lucide-react";',
'import Header from "@/components/Header";',
'import Footer from "@/components/Footer";',
'import ScrollReveal from "@/components/ScrollReveal";',
'',
'const BASE = import.meta.env.BASE_URL;',
'',
'const docs = [',
'  { label: "Mentoring System", href: "https://mits.ac.in/assets/pdf/admin/Mentoring System scan-min.pdf" },',
'  { label: "Mentor Mentee Office Order 2025", href: "https://mits.ac.in/assets/pdf/admin/Mentor Mentee Cell-office order-feb 2025.pdf" },',
'  { label: "Mentor Mentee Office Order 2024", href: "https://mits.ac.in/assets/pdf/admin/Mentor Mentee office Order.pdf" },',
'  { label: "Mentor Coordinators", href: "https://mits.ac.in/assets/pdf/admin/Mentor Coordinators.pdf" },',
'  { label: "Student Mentoring Brochure Guidelines", href: "https://mits.ac.in/assets/pdf/admin/Student Mentoring Brochure Guidelines.pdf" },',
'  { label: "Mentor-Mentee Interaction Forms", href: "http://www.mits.ac.in/assets/pdf/admin/Mentor-Mentee Interaction Forms.pdf" },',
'  { label: "Grading Details", href: "http://www.mits.ac.in/assets/pdf/admin/Grading Details.pdf" },',
'  { label: "Remarks by the Mentor", href: "http://www.mits.ac.in/assets/pdf/admin/Remarks by the Mentor.pdf" },',
'  { label: "MITS-Consolidated Mentoring Meeting Schedules", href: "http://www.mits.ac.in/assets/pdf/admin/MITS-Consolidated Mentoring meeting schedules.pdf" },',
'];',
'',
'const members = [',
'  { sno: 1, name: "Dr. P. Ramanathan", designation: "Principal", position: "Chairman", email: "principal@mits.ac.in" },',
'  { sno: 2, name: "Mrs. U. Vijaya Lakshmi", designation: "Senior Manager - Student Counsellor", position: "Member", email: "vijayalakshmiu@mits.ac.in" },',
'  { sno: 3, name: "Dr. Sudheer Kumar Y", designation: "Assistant Professor - CIVIL", position: "Member", email: "sudheerkumary@mits.ac.in" },',
'  { sno: 4, name: "Mr. G. Mahammed Rafi", designation: "Assistant Professor - EEE", position: "Member", email: "mahammedrafig@mits.ac.in" },',
'  { sno: 5, name: "Dr. Smriti Baruah", designation: "Assistant Professor - ECE", position: "Member", email: "smritib@mits.ac.in" },',
'  { sno: 6, name: "Dr. G. Veeresalingam", designation: "Assistant Professor - MECH", position: "Member", email: "drveerasalingamg@mits.ac.in" },',
'  { sno: 7, name: "Mrs. G. Vasundara Devi", designation: "Assistant Professor - CSE", position: "Member", email: "vasundaradevig@mits.ac.in" },',
'  { sno: 8, name: "Mr. Sreenath K.", designation: "Assistant Professor - AI", position: "Member", email: "sreenathk@mits.ac.in" },',
'  { sno: 9, name: "Dr. M. Kiran Kumar", designation: "Assistant Professor - DS", position: "Member", email: "kirankumarm@mits.ac.in" },',
'  { sno: 10, name: "Mr. T. Niranjan Babu", designation: "Assistant Professor - CS", position: "Member", email: "niranjanbabut@mits.ac.in" },',
'  { sno: 11, name: "Mr. Roni Das", designation: "Assistant Professor - AI & ML", position: "Member", email: "ronidas@mits.ac.in" },',
'  { sno: 12, name: "Mr. Ashok Dasari", designation: "Assistant Professor - CST", position: "Member", email: "ashokd@mits.ac.in" },',
'  { sno: 13, name: "Dr. D. Rajesh Kumar", designation: "Assistant Professor - MBA", position: "Member", email: "drrajeshkumar@mits.ac.in" },',
'  { sno: 14, name: "Mrs. Roopa Prasad", designation: "Assistant Professor - MCA", position: "Member", email: "roopak@mits.ac.in" },',
'  { sno: 15, name: "Dr. Sunku Sreedhar", designation: "Assistant Professor - Physics", position: "Member", email: "drsreedhars@mits.ac.in" },',
'  { sno: 16, name: "Dr. C. V. Raju", designation: "Assistant Professor - Chemistry", position: "Member", email: "drvenkateswararajuc@mits.ac.in" },',
'  { sno: 17, name: "Dr. B. Anitha", designation: "Sr. Assistant Professor", position: "Member", email: "dranithab@mits.ac.in" },',
'  { sno: 18, name: "Dr. Bibin Mathew", designation: "Assistant Professor - Maths", position: "Member", email: "drbibinmathew@mits.ac.in" },',
'  { sno: 19, name: "Dr. M. Parvathi", designation: "Assistant Professor - English", position: "Coordinator", email: "parvathim@mits.ac.in" },',
'];',
]

with open(r'c:\Lokesh\College Website\MITS Website\mits-website\src\components\cells\MmcView.tsx', 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines) + '\n')
print('part1 done')
